version: "3.9"
services:
  postgres:
    container_name: beat-the-machine-postgres
    networks:
      - proxynet
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "beat-the-machine"
    ports:
      - "5432:5432"
    expose:
      - "5432"

networks:
  proxynet:
    name: beat-the-machine-network
