[versions]

coroutines = "1.10.2"
jvmTarget = "21"
konsist = "0.17.3"
kotest = "6.0.4"
kotlin = "2.2.20"
mockk = "1.14.6"
mockkSpring = "4.0.2"
springDependencyManagement = "1.1.7"
springboot = "3.5.6"
swagger = "7.16.0"

[libraries]

# Kotlin & Coroutines
kotlin_core = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin_jackson_module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin_reflection = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx_coroutines_reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinx_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Spring Boot
springboot_actuator_starter = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springboot_jdbc_starter = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
springboot_test_starter = { module = "org.springframework.boot:spring-boot-starter-test" }
springboot_validation_starter = { module = "org.springframework.boot:spring-boot-starter-validation" }
springboot_webflux_starter = { module = "org.springframework.boot:spring-boot-starter-webflux" }

# Testing
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotest_assertions_core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest_extensions_spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest_runner_junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk_core = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk_spring = { module = "com.ninja-squad:springmockk", version.ref = "mockkSpring" }

[plugins]

kotlin_spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
openapi_generator = { id = "org.openapi.generator", version.ref = "swagger" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springboot_dependency_management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }


[bundles]

kotlin_all = [
    "kotlin_core",
    "kotlin_jackson_module",
    "kotlin_reflection",
    "kotlinx_coroutines_core",
    "kotlinx_coroutines_reactor",
]

springboot_all = [
    "springboot_actuator_starter",
    "springboot_jdbc_starter",
    "springboot_validation_starter",
    "springboot_webflux_starter",
]

test_all = [
    "konsist",
    "kotest_assertions_core",
    "kotest_extensions_spring",
    "kotest_runner_junit5",
    "kotlinx_coroutines_test",
    "mockk_core",
    "mockk_spring",
    "springboot_test_starter",
]
